version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install -r app/requirements.txt

  build:
    commands:
      - echo "Building application..."
      - python -m compileall app/
      - echo "Build completed"

  post_build:
    commands:
      - echo "Creating deployment package..."
      - mkdir -p deploy/app
      - cp -r app/* deploy/app/
      - cp app/requirements.txt deploy/
      - cp Procfile deploy/
      - cp nginx.conf deploy/
      - mkdir -p deploy/scripts
      - cp -r scripts/* deploy/scripts/
      - chmod +x deploy/scripts/*.sh
      - cp appspec.yml deploy/
      - cp ec2-deploy-buildspec.yml deploy/
      - cd deploy && zip -r ../app.zip . -x "*.git*" "*.pyc" "*.pyo" "*.pyd" "*.so" "*.egg" "*.egg-info" "__pycache__" "*.swp" "*.swo" "*.bak" "*.tmp" "*.log" "*.pid" "*.pid.lock" "*.lock" "*.DS_Store" "*.idea" "*.vscode" "*.env" "*.venv" "venv/*" "node_modules/*" "*.zip"
      - echo "Deployment package created"

artifacts:
  files:
    - 'app.zip'
    - 'appspec.yml'
    - 'deploy-buildspec.yml'
    - 'ec2-deploy-buildspec.yml'
  name: BuildArtifact 