version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing system dependencies...
      - apt-get update -y
      - apt-get install -y gcc libssl-dev libbz2-dev libffi-dev zlib1g-dev wget unzip
      - echo Installing CodeQL...
      - wget https://github.com/github/codeql-cli-binaries/releases/download/v2.15.4/codeql-linux64.zip
      - unzip codeql-linux64.zip
      - export PATH=$PATH:$PWD/codeql
      - codeql --version
      - wget https://github.com/github/codeql/archive/refs/heads/main.zip -O codeql-queries.zip
      - unzip codeql-queries.zip
      - mv codeql-main/python/ql/src python-queries

  pre_build:
    commands:
      - echo Installing Python dependencies...
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt

  build:
    commands:
      - echo Running tests...
      - python -m pytest tests/ || true
      - echo Collecting static files...
      - python manage.py collectstatic --noinput || true
      - echo Running CodeQL analysis...
      - mkdir -p codeql-db
      - codeql database create codeql-db --language=python --source-root=. || true
      - codeql database analyze codeql-db python-queries --format=sarif-latest --output=codeql-results.sarif || true

artifacts:
  files:
    - '**/*'
    - 'codeql-results.sarif'
  name: ecommerce-app-$(date +%Y-%m-%d-%H-%M-%S)

cache:
  paths:
    - '/root/.cache/pip/**/*'
    - 'codeql-db' 