version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install -r requirements.txt

  build:
    commands:
      - echo "Building application..."
      - python -m compileall .
      - echo "Build completed"

  post_build:
    commands:
      - echo "Creating deployment package..."
      - zip -r ecommerce-app.zip . -x "*.git*" "*.pyc" "*.pyo" "*.pyd" "*.so" "*.egg" "*.egg-info" "__pycache__" "*.swp" "*.swo" "*.bak" "*.tmp" "*.log" "*.pid" "*.pid.lock" "*.lock" "*.DS_Store" "*.idea" "*.vscode" "*.env" "*.venv" "venv/*" "node_modules/*" "*.zip"
      - echo "Deployment package created"

artifacts:
  files:
    - 'ecommerce-app.zip'
    - 'appspec.yml'
    - 'deploy-buildspec.yml'
  name: BuildArtifact 