version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
      nodejs: 16
    commands:
      - echo Installing system dependencies...
      - yum update -y
      - yum install -y gcc openssl-devel bzip2-devel libffi-devel zlib-devel

  pre_build:
    commands:
      - echo Installing Python dependencies...
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt
      - echo Installing frontend dependencies...
      - cd frontend
      - npm install
      - cd ..

  build:
    commands:
      - echo Building frontend...
      - cd frontend
      - npm run build
      - cd ..

artifacts:
  files:
    - '**/*'
  name: ecommerce-app-$(date +%Y-%m-%d-%H-%M-%S)

cache:
  paths:
    - '/root/.cache/pip/**/*' 