version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install awscli
      - pip install -r requirements.txt
      - pip install gunicorn
  build:
    commands:
      - echo Build started on `date`
      - echo Installing dependencies...
      - pip install -r requirements.txt
      - pip install gunicorn

artifacts:
  files:
    - '**/*'
  name: ecommerce-app-$(date +%Y-%m-%d-%H-%M-%S)

cache:
  paths:
    - '/root/.cache/pip/**/*'
    - 'codeql-db' 