version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install -r app/requirements.txt

  build:
    commands:
      - echo "Building application..."
      - python -m compileall app/
      - echo "Build completed"

  post_build:
    commands:
      - echo "Creating deployment package..."
      - mkdir -p deploy/app
      - cp -r app/* deploy/app/
      - cp app/requirements.txt deploy/
      - cp Procfile deploy/
      - cp nginx.conf deploy/
      - cp gunicorn.service deploy/
      - cp gunicorn.socket deploy/
      - cp deploy.sh deploy/
      - cp -r scripts deploy/
      - chmod +x deploy/scripts/*.sh
      - chmod +x deploy/deploy.sh
      - cp appspec.yml deploy/
      - echo "Listing contents of deploy directory before zipping:"
      - ls -la deploy/
      - echo "Listing contents of deploy/scripts directory:"
      - ls -la deploy/scripts/
      - cd deploy
      - zip -r ../app.zip . -x "*.git*" "*.pyc" "*.pyo" "*.pyd" "*.so" "*.egg" "*.egg-info" "__pycache__/*" "*.swp" "*.swo" "*.bak" "*.tmp" "*.log" "*.pid" "*.pid.lock" "*.lock" "*.DS_Store" "*.idea/*" "*.vscode/*" "*.env" "*.venv" "venv/*" "node_modules/*"
      - cd ..
      - echo "Listing contents of zip file:"
      - unzip -l app.zip | grep scripts/
      - echo "Deployment package created"

artifacts:
  files:
    - app.zip
    - appspec.yml
    - deploy.sh
    - ec2-deploy-buildspec.yml
    - gunicorn.service
    - gunicorn.socket
    - nginx.conf
  name: BuildArtifact 