version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
      - pip install gunicorn
  build:
    commands:
      - echo Build started on `date`
      - echo Installing dependencies...
      - pip install -r requirements.txt
      - pip install gunicorn
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Creating Elastic Beanstalk application bundle...
      - zip -r application.zip . -x "*.git*" "*.pyc" "__pycache__/*" "venv/*" "*.pem"

artifacts:
  files:
    - application.zip
  name: BuildArtifact

cache:
  paths:
    - '/root/.cache/pip/**/*'
    - 'codeql-db' 