version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install awscli
      - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - aws configure set region eu-west-1
  build:
    commands:
      - echo Deploying to EC2...
      - chmod +x deploy.sh
      - export EC2_INSTANCE_ID="i-01203af55713a9f83"
      - ./deploy.sh

artifacts:
  files:
    - '**/*'
  name: ecommerce-app-deploy-$(date +%Y-%m-%d-%H-%M-%S) 