version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install awscli
      - aws configure set region eu-west-1
  build:
    commands:
      - echo Deploying to EC2...
      - chmod +x deployment/deploy.sh
      - export EC2_INSTANCE_ID="i-00bb588bfd349593d"
      - ./deployment/deploy.sh

artifacts:
  files:
    - '**/*'
  name: ecommerce-app-deploy-$(date +%Y-%m-%d-%H-%M-%S) 