version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install awscli
  build:
    commands:
      - echo Deploying to EC2...
      - chmod +x deploy.sh
      - ./deploy.sh

artifacts:
  files:
    - '**/*'
  name: ecommerce-app-deploy-$(date +%Y-%m-%d-%H-%M-%S) 