version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - python -m pip install --upgrade pip
      - echo "Creating deployment directory..."
      - mkdir -p /tmp/deploy
      - echo "Unzipping application package..."
      - unzip -o ecommerce-app.zip -d /tmp/deploy
      - echo "Installing requirements..."
      - cd /tmp/deploy
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Preparing for deployment..."
      - echo "Creating SSH directory and setting permissions..."
      - mkdir -p ~/.ssh
      - chmod 700 ~/.ssh
      - echo "Creating SSH key file..."
      - echo "-----BEGIN RSA PRIVATE KEY-----" > ~/.ssh/ecommerce-key.pem
      - echo "MIIEpAIBAAKCAQEAzWZFDhMTM6conzz6rZQP8j/zUjdQOGXBnCEO6gNbzDgW1bwR" >> ~/.ssh/ecommerce-key.pem
      - echo "HvdlLevhOBsQz0Jg9YBANhDgKKDM4ny5fwTQom0rwMOLTpqwcxLtc4hCevUvlOkI" >> ~/.ssh/ecommerce-key.pem
      - echo "hc4K/YSxb9du/2wqJ217v5Cul+SDGlgmrUGLqYqYVtHa8duWc3qJ9zC0MmqjcVui" >> ~/.ssh/ecommerce-key.pem
      - echo "R4cGa0zYvDxHobTS5e/obp90uKqBNwFerDoKyy9xVbEw1NPC05rA72VWUJWRA9Mw" >> ~/.ssh/ecommerce-key.pem
      - echo "UERjZPYg+6oUlfgAw8suJXoNy/fm7qUemN4prB8/VfnfZJuFcUr1Fc2RHz3Ilo2u" >> ~/.ssh/ecommerce-key.pem
      - echo "Sd0OHBR7MI2UUbI8u/SaqLQ+r68a4/fsm9+T+QIDAQABAoIBAHhGMpmTQeM1NuxH" >> ~/.ssh/ecommerce-key.pem
      - echo "4OJTmSLZn7m8+hSMQVsTYJBXdyGWloiBn+TqKS1CupcIAkfbLruTZgZCy3/+6PqW" >> ~/.ssh/ecommerce-key.pem
      - echo "3mgqgaEbHEu8NY7JthksNC860vL9L+earYrspDLfyKcdF7optGVyDsyWBCadgMek" >> ~/.ssh/ecommerce-key.pem
      - echo "ZsF9aDLXHW15ZSPK2ca1MqS0uE/sZJM2mZLcEcWVb2jOJswiYhE7+ieeoFHIbbGj" >> ~/.ssh/ecommerce-key.pem
      - echo "wB0uQcrNjJJs/4XFco0QCyHK9kmuJaqroOMAMjWt94knkC6eo1oKS8pe5VEd9LqR" >> ~/.ssh/ecommerce-key.pem
      - echo "yUwbxsFeKxvvBVDGz+nXiClstyFnJj89Gyl9rH6cE9MuvyMVSDoYAf7klFPHUdy6" >> ~/.ssh/ecommerce-key.pem
      - echo "cZxp7SECgYEA9rXvQio7EvzUIB5V46vq3r2vOVqUWrDSGAa+gAjnpLn3NFHBrJj2" >> ~/.ssh/ecommerce-key.pem
      - echo "0oEc7Ru2dToQMKoZ52ewTO9SH9W0TCfALJbNDe+lYkxjrcY6HDJHFcgFRoaQ3Jaj" >> ~/.ssh/ecommerce-key.pem
      - echo "RuMOgoi4h+d20DejaOm4V01ppw3P2I6DwHUZ4pn0ug0q4lDkebKA+XcCgYEA1SIi" >> ~/.ssh/ecommerce-key.pem
      - echo "Dp0gKMmFOqE5l39A64qDh53HDz9yzeCujU0J7v/F7lphEV7I+jtQJO6Xt7KkcKzc" >> ~/.ssh/ecommerce-key.pem
      - echo "RQWaTAAgQr3mq9aOzakV/sWHgPcLkMhQg4JA7L0qDwzSMDiRnZjpxOO3llT686HC" >> ~/.ssh/ecommerce-key.pem
      - echo "3tBr3YXfDvNjQu2UIH2AEzcaU6ROfxkoYTOUOg8CgYBYjwQ8hvY/oZvvj5QbLqoX" >> ~/.ssh/ecommerce-key.pem
      - echo "nJVajCY2y8QOtdUKFqg4HD0dfb982ke3VntwrYL4X4hSP60ewLyrUTj0jnyy3Y4B" >> ~/.ssh/ecommerce-key.pem
      - echo "M3yV5RFD0NHzHfXcCzwzGGK0Zzd2x2gC2RxrRPKgbjjbEy3ISiVOyU4EllOmk7m9" >> ~/.ssh/ecommerce-key.pem
      - echo "iwtoqQUNCA79wDXTbX0YjwKBgQDAf6uy90dsj1a9tZCGvHCuTNSvUFnR88SFHkGJ" >> ~/.ssh/ecommerce-key.pem
      - echo "beNi8bCbrxWs0qdDGv8v3C87wyWyfu4TiRPrQNHidhI5cfhY2Db9fPr+CCNyCPpv" >> ~/.ssh/ecommerce-key.pem
      - echo "TN3G9LNgFHxjATTD2rCJHANczDQ8iAWxqR1DXv4wSrOEZ4A6OB/NOx+UG/qp4NcP" >> ~/.ssh/ecommerce-key.pem
      - echo "s75VEQKBgQC8vA7kSLOYb/GxOecrAcMQaYI0/DMFKapblV/u9/en+Eu0HT4Pk1EI" >> ~/.ssh/ecommerce-key.pem
      - echo "neQeF+4iFF4auZHKbcDTLhtvEbqBUIj5lbcz4O3tUf8JLFjkFg4pMq97tOH1ZtDd" >> ~/.ssh/ecommerce-key.pem
      - echo "QcFietk+zHsk+P/BBrUWVw17vYCIATqciaT4NfW+5fOB8SsJCqPrMg==" >> ~/.ssh/ecommerce-key.pem
      - echo "-----END RSA PRIVATE KEY-----" >> ~/.ssh/ecommerce-key.pem
      - echo "Setting key permissions..."
      - chmod 400 ~/.ssh/ecommerce-key.pem
      - echo "Verifying key permissions and content..."
      - ls -la ~/.ssh/ecommerce-key.pem
      - head -n 1 ~/.ssh/ecommerce-key.pem
      - echo "Current directory:"
      - pwd
      - echo "Contents of deployment package:"
      - ls -la /tmp/deploy

  build:
    commands:
      - echo "Starting deployment..."
      - echo "Current directory $(pwd)"
      - echo "Listing files"
      - ls -la
      - echo "Testing SSH connection with verbose output..."
      - ssh -v -o StrictHostKeyChecking=no -i ~/.ssh/ecommerce-key.pem ec2-user@ec2-34-243-69-123.eu-west-1.compute.amazonaws.com "echo 'SSH connection test'"
      - echo "Creating target directory on EC2"
      - ssh -o StrictHostKeyChecking=no -i ~/.ssh/ecommerce-key.pem ec2-user@ec2-34-243-69-123.eu-west-1.compute.amazonaws.com "sudo mkdir -p /var/www/html/ecommerce && sudo chown ec2-user:ec2-user /var/www/html/ecommerce"
      - echo "Copying application files to EC2"
      - scp -o StrictHostKeyChecking=no -i ~/.ssh/ecommerce-key.pem -r /tmp/deploy/app/* ec2-user@ec2-34-243-69-123.eu-west-1.compute.amazonaws.com:/var/www/html/ecommerce/
      - echo "Restarting application"
      - ssh -o StrictHostKeyChecking=no -i ~/.ssh/ecommerce-key.pem ec2-user@ec2-34-243-69-123.eu-west-1.compute.amazonaws.com "cd /var/www/html/ecommerce && sudo systemctl restart ecommerce-app"

  post_build:
    commands:
      - echo "Deployment completed successfully"

artifacts:
  files:
    - '**/*'
  name: DeployArtifact 