version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - echo "Current directory:"
      - pwd
      - echo "Directory contents:"
      - ls -la
      - echo "Checking for requirements.txt in different locations:"
      - find . -name requirements.txt
      - pip install --upgrade pip
      - pip install awscli
      - if [ -f "requirements.txt" ]; then
          echo "Found requirements.txt in root directory";
          pip install -r requirements.txt;
        elif [ -f "app/requirements.txt" ]; then
          echo "Found requirements.txt in app directory";
          pip install -r app/requirements.txt;
        elif [ -f "deploy/requirements.txt" ]; then
          echo "Found requirements.txt in deploy directory";
          pip install -r deploy/requirements.txt;
        else
          echo "requirements.txt not found in any expected location";
          exit 1;
        fi

  pre_build:
    commands:
      - echo "Starting deployment to EC2..."
      - echo "Current directory structure:"
      - ls -R

  build:
    commands:
      - echo "Deploying application..."
      - sudo mkdir -p /var/www/html/ecommerce
      - sudo cp -r * /var/www/html/ecommerce/ || echo "Copy failed, checking directory contents:"
      - ls -la /var/www/html/ecommerce/
      - cd /var/www/html/ecommerce
      - python3 -m venv venv
      - source venv/bin/activate
      - if [ -f "requirements.txt" ]; then
          pip install -r requirements.txt;
        elif [ -f "app/requirements.txt" ]; then
          pip install -r app/requirements.txt;
        else
          echo "requirements.txt not found in deployment directory";
          exit 1;
        fi
      - sudo systemctl restart nginx || echo "Failed to restart nginx"
      - sudo systemctl restart gunicorn || echo "Failed to restart gunicorn"

  post_build:
    commands:
      - echo "Application deployment completed"
      - echo "Final directory structure:"
      - ls -R /var/www/html/ecommerce/ 