version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - echo "Current directory:"
      - pwd
      - echo "Directory contents:"
      - ls -la
      - echo "Checking for requirements.txt in different locations:"
      - find . -name requirements.txt
      - pip install --upgrade pip
      - pip install awscli
      - pip install boto3

  pre_build:
    commands:
      - echo "Preparing for deployment..."
      - echo "Unzipping application package..."
      - unzip -o ecommerce-app.zip -d /tmp/deploy
      - echo "Contents of deployment package:"
      - ls -la /tmp/deploy

  build:
    commands:
      - echo "Installing application dependencies..."
      - cd /tmp/deploy
      - pip install -r requirements.txt
      - echo "Setting up application directory..."
      - sudo mkdir -p /var/www/html/ecommerce
      - sudo cp -r * /var/www/html/ecommerce/
      - sudo chown -R ubuntu:ubuntu /var/www/html/ecommerce
      - echo "Setting up virtual environment..."
      - sudo -u ubuntu python3 -m venv /var/www/html/ecommerce/venv
      - sudo -u ubuntu /var/www/html/ecommerce/venv/bin/pip install -r /var/www/html/ecommerce/requirements.txt

  post_build:
    commands:
      - echo "Starting application..."
      - sudo systemctl daemon-reload
      - sudo systemctl enable gunicorn
      - sudo systemctl start gunicorn
      - echo "Deployment completed successfully"

artifacts:
  files:
    - '**/*'
  name: DeployArtifact 