version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
      - pip install awscli

  pre_build:
    commands:
      - echo "Starting deployment to EC2..."

  build:
    commands:
      - echo "Deploying application..."
      - mkdir -p /var/www/html/ecommerce
      - cp -r * /var/www/html/ecommerce/
      - cd /var/www/html/ecommerce
      - python3 -m venv venv
      - source venv/bin/activate
      - pip install -r requirements.txt
      - sudo systemctl restart nginx
      - sudo systemctl restart gunicorn

  post_build:
    commands:
      - echo "Application deployment completed" 