version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Installing Session Manager plugin..."
      - curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
      - sudo dpkg -i session-manager-plugin.deb
      - rm session-manager-plugin.deb

  build:
    commands:
      - echo "Creating deployment package..."
      - tar -czf deploy.tar.gz app/
      - echo "Uploading to S3..."
      - aws s3 cp deploy.tar.gz s3://ecommerce-app-deploy/deploy.tar.gz --region eu-west-1
      - echo "Deploying to EC2 instance..."
      - >
        aws ssm send-command --instance-ids "i-0a423fae01494c799" 
        --document-name "AWS-RunShellScript" 
        --comment "Create deployment directory" 
        --parameters '{"commands":["sudo mkdir -p /var/www/html/ecommerce"]}' 
        --region eu-west-1
      - >
        aws ssm send-command --instance-ids "i-0a423fae01494c799" 
        --document-name "AWS-RunShellScript" 
        --comment "Deploy application from S3" 
        --parameters '{"commands":["cd /var/www/html/ecommerce && aws s3 cp s3://ecommerce-app-deploy/deploy.tar.gz . && tar -xzf deploy.tar.gz && rm deploy.tar.gz"]}' 
        --region eu-west-1
      - echo "Deployment completed. Application URL: http://ec2-34-243-69-123.eu-west-1.compute.amazonaws.com"

artifacts:
  files:
    - "**/*"
  name: DeployArtifact
