version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - ls -la  # Debug: List files to verify requirements.txt exists
      - pwd     # Debug: Print current directory
      - pip install --upgrade pip
      - pip install awscli
      - if [ -f "app/requirements.txt" ]; then pip install -r app/requirements.txt; elif [ -f "requirements.txt" ]; then pip install -r requirements.txt; else echo "requirements.txt not found" && exit 1; fi

  pre_build:
    commands:
      - echo "Starting deployment to EC2..."

  build:
    commands:
      - echo "Deploying application..."
      - sudo mkdir -p /var/www/html/ecommerce
      - sudo cp -r * /var/www/html/ecommerce/
      - cd /var/www/html/ecommerce
      - python3 -m venv venv
      - source venv/bin/activate
      - if [ -f "app/requirements.txt" ]; then pip install -r app/requirements.txt; elif [ -f "requirements.txt" ]; then pip install -r requirements.txt; else echo "requirements.txt not found" && exit 1; fi
      - sudo systemctl restart nginx || echo "Failed to restart nginx"
      - sudo systemctl restart gunicorn || echo "Failed to restart gunicorn"

  post_build:
    commands:
      - echo "Application deployment completed" 