version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install awscli

  build:
    commands:
      - echo "Starting deployment..."
      - chmod +x deploy.sh
      - EC2_HOST="ec2-52-214-107-96.eu-west-1.compute.amazonaws.com" EC2_USER="ubuntu" KEY_PATH="/tmp/deploy_key" ./deploy.sh

artifacts:
  files:
    - '**/*'
  name: DeployArtifact 