version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install awscli
      - pip install boto3

  pre_build:
    commands:
      - echo "Preparing for deployment..."
      - echo "Unzipping application package..."
      - unzip -o ecommerce-app.zip -d /tmp/deploy
      - echo "Contents of deployment package:"
      - ls -la /tmp/deploy

  build:
    commands:
      - echo "Deploying to EC2 instance..."
      - aws s3 cp /tmp/deploy/ecommerce-app.zip s3://ecommerce-app-pipeline-artifacts/
      - echo "Downloading application to EC2..."
      - aws ssm send-command --instance-ids i-00bb588bfd349593d --document-name AWS-RunShellScript --parameters 'commands=["cd /tmp && aws s3 cp s3://ecommerce-app-pipeline-artifacts/ecommerce-app.zip ."]' --region eu-west-1
      - echo "Unzipping application..."
      - aws ssm send-command --instance-ids i-00bb588bfd349593d --document-name AWS-RunShellScript --parameters 'commands=["unzip -o /tmp/ecommerce-app.zip -d /var/www/html/ecommerce"]' --region eu-west-1
      - echo "Setting up Python virtual environment..."
      - aws ssm send-command --instance-ids i-00bb588bfd349593d --document-name AWS-RunShellScript --parameters 'commands=["cd /var/www/html/ecommerce && python3 -m venv venv && venv/bin/pip install -r requirements.txt"]' --region eu-west-1
      - echo "Starting Gunicorn server..."
      - aws ssm send-command --instance-ids i-00bb588bfd349593d --document-name AWS-RunShellScript --parameters 'commands=["cd /var/www/html/ecommerce && nohup venv/bin/gunicorn --bind 0.0.0.0:5000 app:app > gunicorn.log 2>&1 &"]' --region eu-west-1

  post_build:
    commands:
      - echo "Deployment completed successfully"

artifacts:
  files:
    - '**/*'
  name: DeployArtifact 