version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - python -m pip install --upgrade pip
      - echo "Creating deployment directory..."
      - mkdir -p /tmp/deploy
      - echo "Unzipping application package..."
      - unzip -o ecommerce-app.zip -d /tmp/deploy
      - echo "Installing requirements..."
      - cd /tmp/deploy
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Preparing for deployment..."
      - echo "Creating SSH directory and setting permissions..."
      - mkdir -p ~/.ssh
      - chmod 700 ~/.ssh
      - echo "Retrieving SSH key from Parameter Store..."
      - aws ssm get-parameter --name /ecommerce/ssh-key --with-decryption --query Parameter.Value --output text > ~/.ssh/ecommerce-key.pem
      - echo "Setting key permissions..."
      - chmod 400 ~/.ssh/ecommerce-key.pem
      - echo "Verifying key permissions and content..."
      - ls -la ~/.ssh/ecommerce-key.pem
      - head -n 1 ~/.ssh/ecommerce-key.pem
      - echo "Current directory:"
      - pwd
      - echo "Contents of deployment package:"
      - ls -la /tmp/deploy

  build:
    commands:
      - echo "Starting deployment..."
      - echo "Current directory $(pwd)"
      - echo "Listing files"
      - ls -la
      - echo "Testing SSH connection with verbose output..."
      - ssh -v -o StrictHostKeyChecking=no -i ~/.ssh/ecommerce-key.pem ec2-user@ec2-34-243-69-123.eu-west-1.compute.amazonaws.com "echo 'SSH connection test'"
      - echo "Creating target directory on EC2"
      - ssh -o StrictHostKeyChecking=no -i ~/.ssh/ecommerce-key.pem ec2-user@ec2-34-243-69-123.eu-west-1.compute.amazonaws.com "sudo mkdir -p /var/www/html/ecommerce && sudo chown ec2-user:ec2-user /var/www/html/ecommerce"
      - echo "Copying application files to EC2"
      - scp -o StrictHostKeyChecking=no -i ~/.ssh/ecommerce-key.pem -r /tmp/deploy/app/* ec2-user@ec2-34-243-69-123.eu-west-1.compute.amazonaws.com:/var/www/html/ecommerce/
      - echo "Restarting application"
      - ssh -o StrictHostKeyChecking=no -i ~/.ssh/ecommerce-key.pem ec2-user@ec2-34-243-69-123.eu-west-1.compute.amazonaws.com "cd /var/www/html/ecommerce && sudo systemctl restart ecommerce-app"

  post_build:
    commands:
      - echo "Deployment completed successfully"

artifacts:
  files:
    - '**/*'
  name: DeployArtifact 