version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install -r app/requirements.txt
      - pip install pylint

  build:
    commands:
      - echo "Running pylint..."
      - pylint app/ > pylint_report.txt || true

artifacts:
  files:
    - 'pylint_report.txt'
  name: TestArtifact 