version: 0.2

phases:
  install:
    commands:
      - pip install pylint
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Running Pylint analysis..."
      - pylint --output-format=json app/ > pylint-report.json || true
      - echo "Pylint analysis completed"
      - mkdir -p test-artifacts
      - cp pylint-report.json test-artifacts/

reports:
  pylint:
    files:
      - 'pylint-report.json'
    file-format: 'JSON'
    base-directory: '.'

artifacts:
  files:
    - 'test-artifacts/**/*'
  name: TestArtifacts 