version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install pytest pytest-cov pylint

  pre_build:
    commands:
      - echo "Running pylint..."
      - pylint --output-format=text app/app.py > pylint-report.txt

  build:
    commands:
      - echo "Running tests..."
      - pytest --cov=. --cov-report=xml

artifacts:
  files:
    - coverage.xml
    - pylint-report.txt
  name: TestResults 