name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov pylint
      
      - name: Run tests
        run: |
          pytest --cov=. --cov-report=xml
      
      - name: Run pylint
        run: |
          pylint --output-format=text app.py > pylint-report.txt

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      
      - name: Deploy to EC2
        run: |
          # Add your deployment commands here
          ssh -i ${{ secrets.SSH_KEY }} ubuntu@ec2-63-33-199-126.eu-west-1.compute.amazonaws.com "cd /var/www/ecommerce && git pull && sudo systemctl restart ecommerce" 